package kr.co.leehana.type;

/**
 * @author Hana Lee
 * @since 2015-12-19 20:28
 */
public enum MessageType {

	START, GUESS_NUM, JOIN, GET_ROOM_LIST, CREATE_ROOM, GET_SETTING, SET_SETTING, LOGIN, LOGOUT, GET_READY_STATE, SET_GENERATION_NUMBER, ALL_USER_COMPLETED_GUESS, ALL_USER_GUESS_COMPLETE_STATE_RESET, DEPENDER_ALREADY_EXIST, GET_DEPENDER_SCORE, READY
}